version: '3'
volumes:
  data:
services:
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
